pepfile: config/pep/config.yaml

data: /homes/adrian/mdr_mtb-master/data

gene_loc: "/resources/gene_loci.csv"
# virus genome to use as reference. Must be a NCBI accession
bacterium-reference-genome:
  - NC_000962.3

mtb-genome-download-path:
  - ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/195/955/GCA_000195955.2_ASM19595v2/GCA_000195955.2_ASM19595v2_genomic.fna.gz

human-genome-download-path:
  - ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.28_GRCh38.p13/GCA_000001405.28_GRCh38.p13_genomic.fna.gz

illumina_adapters:
  - -a CTGTCTCTTATACACATCT -g AGATGTGTATAAGAGACAG

preprocessing:
  amplicon-reference: "AL123456"
  amplicon-ref-ver: "AL123456.3"

reduce_reads:
  reducing: False
  parameters: 40 # how many reads should be reduced in percent