pepfile: config/pep/config.yaml

data: /homes/adrian/mdr_mtb-master/data

sample_table: "samples.csv"

# virus genome to use as reference. Must be a NCBI accession
bacterium-reference-genome:
  - NC_000962.3

human-genome-download-path:
  - ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.28_GRCh38.p13/GCA_000001405.28_GRCh38.p13_genomic.fna.gz

preprocessing:
  amplicon-primers: "resources/nCoV-2019.primer.bed"
  # GenBank accession of reference sequence of the amplicon primers
  amplicon-reference: "AL123456"
