name: Essential file check
run-name: Checking repository for essential files
on: [push]

jobs:
  Testing-folder-structure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: "workflow/Snakefile, 
          resources/pointfinder_db/mycobacterium_tuberculosis/resistens-overview.txt,
          resources/gene_loci.csv, 
          config/config.yaml, 
          config/pep/samples.csv"

      - name: Files exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: echo All files exists!
      
      - name: File is missing
        if: steps.check_files.outputs.files_exists == 'false'
        run: |
          echo Some necessary files are missing. Check directory build
          exit 1