name: Pipeline Test
run-name: Checking workflow process
on: [push]

jobs:
  Run_pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Test workflow
      uses: snakemake/snakemake-github-action@v1
      with:
        directory: '.tests'
        snakefile: 'workflow/Snakefile'
        args: "--use-conda --show-failed-logs -j 2 --conda-cleanup-pkgs"

    - name: Set result env
      run: |
        echo: "result=$(cat .tests/results/summary/ABres/10_S40002reduced/ABres_10_S40002reduced.csv)" >> $GITHUB_ENV

    - name: File contents
      if: contains(env.result, 'RIFAMPICIN')
      run: |
        echo "found contained ABR"
        echo "env.result"