name: Pipeline Test
on: [push]

jobs:
  Run_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: snakemake/snakemake-github-action@v1
        with:
          directory: '.tests'
          snakefile: 'workflow/Snakefile'
          args: "--use-conda --show-failed-logs -j 2 --conda-cleanup-pkgs"