name: Test pipeline run
run-name: Checking workflow process
on: [push]

jobs:
  Run_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test workflow
        uses: snakemake/snakemake-github-action@v1
        with:
          directory: '.tests'
          snakefile: 'workflow/Snakefile'
          args: "--use-conda --show-failed-logs -j 2 --conda-cleanup-pkgs"

      - name: Set up Python environment
        run: |
          chmod +x .tests/setup-python-env.sh
          ./.tests/setup-python-env.sh
        shell: bash

      - name: Verify Antibiogramm
        run: |
          source .tests/venv/bin/activate
          python .tests/resources/check_result.py