name: Pipeline Test
run-name: Checking workflow process
on: [push]

jobs:
  Run_pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Test workflow
      uses: snakemake/snakemake-github-action@v1
      with:
        directory: '.tests'
        snakefile: 'workflow/Snakefile'
        args: "--use-conda --show-failed-logs -j 2 --conda-cleanup-pkgs"

    - name: Setup miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        miniforge-variant: Mambaforge
        channels: conda-forge
        python-version: 3.9
        activate-environment: pandas
        environment-file: .tests/pandas.yml
        use-mamba: true

    - name: Verify Antibiogramm
      run: |
        python check_results.py
      working-directory: .tests/results/summary/ABres/10_S40002reduced/ABres_10_S40002reduced.csv