name: test-github-actions
run-name: ${{ github.actor }} is testing github actions
on: [push]
jobs:
  Testing-folder-structure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: "Snakefile, resources/pointfinder_db/mycobacterium-tuberculosis/resistens-overview.txt, config/config.yaml, config/pep/samples.csv"

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: echo All files exists!
        if: steps.check_files.outputs.files_exists == 'false'
        with:
          script: |
            core.setFailed('Some necessary files are missing. Check directory build') 